//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ocrFileVeriProc {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ocrFileVeriProc.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutVerNo {
            get {
                return ResourceManager.GetString("AboutVerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↓ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrowDn {
            get {
                return ResourceManager.GetString("ArrowDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrowUp {
            get {
                return ResourceManager.GetString("ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image folder and Destination folder should not be the same. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BothFoldersAreSame {
            get {
                return ResourceManager.GetString("BothFoldersAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished processing files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder not exits. Please specify the folder path for destination first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderNotExistsDst {
            get {
                return ResourceManager.GetString("FolderNotExistsDst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder not exits. Please specify the folder path for image files first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderNotExistsImg {
            get {
                return ResourceManager.GetString("FolderNotExistsImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following error(s) occurred while loading ocr_params.ini. Default setting will be applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IniErrorMsg {
            get {
                return ResourceManager.GetString("IniErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting file error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IniErrorTitle {
            get {
                return ResourceManager.GetString("IniErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify keywords. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeywordsRequired {
            get {
                return ResourceManager.GetString("KeywordsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No image file was found in the folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoImageFiles {
            get {
                return ResourceManager.GetString("NoImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing: {0} / {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of image files in folder: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result0Total {
            get {
                return ResourceManager.GetString("Result0Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result1Deleted {
            get {
                return ResourceManager.GetString("Result1Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moved: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result1Moved {
            get {
                return ResourceManager.GetString("Result1Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verified: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result1Verified {
            get {
                return ResourceManager.GetString("Result1Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kept: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result2Kept {
            get {
                return ResourceManager.GetString("Result2Kept", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result3Error {
            get {
                return ResourceManager.GetString("Result3Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total processing time (sec): {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result4Time {
            get {
                return ResourceManager.GetString("Result4Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
