//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ocrFileVeriProc {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILangs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILangs() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ocrFileVeriProc.UILangs", typeof(UILangs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   العربية に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   বাংলা に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string bn {
            get {
                return ResourceManager.GetString("bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deutsch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Español に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   فارسی に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Français に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   हिन्दी に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bahasa Indonesia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italiano に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basa Jawa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string jv {
            get {
                return ResourceManager.GetString("jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   मराठी に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mr {
            get {
                return ResourceManager.GetString("mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bahasa Melayu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ਪੰਜਾਬੀ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pa {
            get {
                return ResourceManager.GetString("pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nigerian Pidgin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pcm {
            get {
                return ResourceManager.GetString("pcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Português に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Русский に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kiswahili に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sw {
            get {
                return ResourceManager.GetString("sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   தமிழ் に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   తెలుగు に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string te {
            get {
                return ResourceManager.GetString("te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ไทย に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string th {
            get {
                return ResourceManager.GetString("th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tagalog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tl {
            get {
                return ResourceManager.GetString("tl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkçe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Українська に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string uk {
            get {
                return ResourceManager.GetString("uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tiếng Việt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string vi {
            get {
                return ResourceManager.GetString("vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   吴语 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wuu {
            get {
                return ResourceManager.GetString("wuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   简体中文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zh_Hans {
            get {
                return ResourceManager.GetString("zh_Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   繁體中文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zh_Hant {
            get {
                return ResourceManager.GetString("zh_Hant", resourceCulture);
            }
        }
    }
}
